### ISSUE TITLE
Bugs Report 14.10.2018

### ISSUE THREAD

**Issue by OgiJr** [BobbyRaduloff/CouncilTrack#7]
# Submit page
Expected Behaviour
The submit page should tell you that there are no events.
Actual Behaviour
Only an empty form appears.
Steps
Delete all events and open submit.
*Apply to:*
View, Submit, Delete Event, Delete User.

# Adding events
You cannot remove an item after you have added 
Recreation Steps
Add an item while creating an event and then try to delete it.

# Event creation
If you fail to create an event if you go back the site will give you an error: "Потвърдете повторното изпращане на формуляра"
If you click on the text of a checkbox it should be ticked.
If you add a new item while creating an event it clears all other fields

# Login Page
Expected Behaviour
The page shouldn't respond when you click on the header in the login page. (also if we could change the cursor when you hover over it)
Actual Behaviour
When in you click on the header in the login page it tells you that you are not logged in.

**Comment by BobbyRaduloff** [comment]
Almost all the bugs were fixed, except the: confirm page re-submission error as I couldn't replicate it and the item removal one. This one will require too much of a rewrite that I'd rather do new features right now.

These bugs were fixed in GH-8. Would love some more testing on if the bug fixes work, @OgiJr .
